production:
    secret_token: <%= ENV['SECRET_TOKEN'] %>
    secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

development:
  secret_token: ENV['SECRET_TOKEN'] 
  secret_key_base: ENV['SECRET_KEY_BASE']
  # secret_key_base: "abcdef0123456789"
